name: DTIENV
channels:
  - conda-forge
  - anaconda
  - pytorch
  - nvidia
  - defaults
channel_priority: flexible
dependencies:
  - python=3.12.5
  - torchvision=0.19.1
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - pip
  - pip:
    - torch-geometric==2.6.0
    - ray==2.36.0
    - biopython
    - rdkit
    - torchmetrics
    - uvloop
