# this config file is used for running the template default tests

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: null 
  filename: "checkpoint_{epoch:03d}-{val_loss:.4f}-{val_auc:.4f}"
  monitor: val_auc
  verbose: False
  save_last: True
  save_top_k: 5 
  mode: "max" 
  auto_insert_metric_name: True
  save_weights_only: False 
  every_n_train_steps: null 
  train_time_interval: null 
  every_n_epochs: 1 
  save_on_train_epoch_end: null 

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_auc
  min_delta: 5.0e-5
  patience: 30
  verbose: False 
  mode: "max"
  strict: True 
  check_finite: True 
  stopping_threshold: null
  divergence_threshold: null 
  check_on_train_epoch_end: null


