_target_: datamodule.dataloader.UNIDataModule

dm_cfg:
  batch_size: 128
  num_workers: 4

splitting:
  ratio: [0.65,0.15,0.20]
  balanced: True
  unbalanced_ratio: 10 
  splitting_strategy: 'random'  #random, cold_drug, cold_target
  seed: 42

serializer:
  load_serialized: True
  target_name: "bindingDB_${preprocess.label}_ESM.pt"
  drug_name: "bindingDB_${preprocess.label}_PubChem10M.pt"
  save_path: './datasets/serialized/'
