_target_: datamodule.dataloader_GAT.UNIDataModule

dm_cfg:
  batch_size: 128
  num_workers: 4

splitting:
    ratio: ''

serializer:
  load_serialized: True
  target_name: 'hetionet_ESM.pt'
  drug_name: 'hetionet_PubChem10M.pt'
  save_path: './datasets/serialized/'
  
  #
  
