cfg['datamodule']['dm_cfg']['batch_size']: 512
cfg['module']['optimizer']['lr']: 0.00033043332334629157
cfg['module']['network']['layers']: [512, 256, 128] 
cfg['module']['network']['dropout']: 0.1
cfg['module']['network']['activation_fn']: "'ReLU'"
cfg['module']['optimizer']['weight_decay']: 0.00031198854025985776
cfg['module']['optimizer']['optimizer']: "'Adam'"