cfg['datamodule']['dm_cfg']['batch_size']: 128
cfg['module']['optimizer']['lr']: 0.00018537215408339093
cfg['module']['network']['layers']: [256, 128]
cfg['module']['network']['dropout']: 0.2
cfg['module']['network']['activation_fn']: "'ReLU'"
cfg['module']['optimizer']['weight_decay']: 0.0006755020499865177
cfg['module']['optimizer']['optimizer']: "'Adam'"
cfg['module']['GAT_params']['drug_gat']['out_channels']: 64
cfg['module']['GAT_params']['drug_gat']['heads']: 2
cfg['module']['GAT_params']['drug_gat']['dropout']: 0.2
cfg['module']['GAT_params']['drug_gat']['add_self_loops']: False
cfg['module']['GAT_params']['drug_gat']['num_layers']: 2
cfg['module']['GAT_params']['prot_gat']['out_channels']: 128
cfg['module']['GAT_params']['prot_gat']['heads']: 2
cfg['module']['GAT_params']['prot_gat']['dropout']: 0.1
cfg['module']['GAT_params']['prot_gat']['add_self_loops']: True
cfg['module']['GAT_params']['prot_gat']['num_layers']: 2
cfg['module']['GAT_params']['drug_gat']['threshold']: 0.02057027165409946
cfg['module']['GAT_params']['prot_gat']['threshold']: 0.010648444892670111
