cfg['datamodule']['dm_cfg']['batch_size']: 1280
cfg['module']['optimizer']['lr']: 0.0003812893838038673
cfg['module']['network']['layers']: [256, 128, 64] 
cfg['module']['network']['dropout']: 0.1
cfg['module']['network']['activation_fn']: "'ReLU'"
cfg['module']['optimizer']['weight_decay']: 4.54351313609667e-05
cfg['module']['optimizer']['optimizer']: "'Adam'"
cfg['module']['GAT_params']['drug_gat']['out_channels']: 96
cfg['module']['GAT_params']['drug_gat']['heads']: 8
cfg['module']['GAT_params']['drug_gat']['dropout']: 0.3
cfg['module']['GAT_params']['drug_gat']['add_self_loops']: False
cfg['module']['GAT_params']['drug_gat']['num_layers']: 4
cfg['module']['GAT_params']['prot_gat']['out_channels']: 160
cfg['module']['GAT_params']['prot_gat']['heads']: 8
cfg['module']['GAT_params']['prot_gat']['dropout']: 0.2
cfg['module']['GAT_params']['prot_gat']['add_self_loops']: True
cfg['module']['GAT_params']['prot_gat']['num_layers']: 2
